mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    displayName: "New User",
    email: "newuser@example.com",
    userId_expr: "auth.uid"
  })
}

query GetProjects @auth(level: USER) {
  projects {
    id
    name
  }
}

mutation UpdateProjectName($id: UUID!, $name: String!) @auth(level: USER) {
  project_update(key: {id: $id}, data: {name: $name})
}

query ListPublicProjects @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  projects {
    id
    name
    projectId
  }
}